Object.is()
Object.keys()
Object.values()
Object.entries()
Object.fromEntries()
Object.freeze()
Object.isFrozen()
Object.seal()
Object.isSealed()
Object.assign()
Object.prototype.hasOwnProperty.call()
Object.prototype.toString.call()

Array.isArray()
Array().fill()
Array.from()
